"use client";
import { BarChart3, BriefcaseBusiness, Download, FolderKanban, LogOut, Menu, MessageSquareText, Package, Save, Search, Settings, Star, Users, Wrench, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { ChangeEvent, useMemo, useState } from "react";

const sections=[["projects",FolderKanban],["packages",Package],["testimonials",Star],["services",Wrench],["team",Users],["hero",BriefcaseBusiness],["gallery",FolderKanban],["settings",Settings],["seo",Search]] as const;

export function AdminDashboard({initial}:{initial:{site:Record<string,unknown>;leads:Array<Record<string,unknown>>}}){
 const [site,setSite]=useState(initial.site);const [leads,setLeads]=useState(initial.leads);const [tab,setTab]=useState("overview");const [mobile,setMobile]=useState(false);const [saved,setSaved]=useState(false);const [search,setSearch]=useState("");const [status,setStatus]=useState("All");const [upload,setUpload]=useState("");const router=useRouter();
 const counts=useMemo(()=>({leads:leads.length,new:leads.filter(x=>x.status==="New").length,projects:(site.projects as unknown[]||[]).length,packages:(site.packages as unknown[]||[]).length,testimonials:(site.testimonials as unknown[]||[]).length}),[leads,site]);
 async function save(){const r=await fetch("/api/admin/data",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({site,leads})});if(r.ok){setSaved(true);setTimeout(()=>setSaved(false),1800)}}
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.push("/admin/login");router.refresh()}
 function updateJson(key:string,value:string){try{setSite({...site,[key]:JSON.parse(value)})}catch{}}
 async function uploadImage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:form});const j=await r.json();setUpload(r.ok?`Uploaded: ${j.path}`:j.error)}
 const filtered=leads.filter(x=>(status==="All"||x.status===status)&&`${x.name} ${x.mobile} ${x.location} ${x.source}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="admin-app"><aside className={mobile?"admin-sidebar open":"admin-sidebar"}><div className="admin-logo"><span>RS</span><div><strong>Construction</strong><small>Administration</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}><BarChart3/>Overview</button><button className={tab==="leads"?"active":""} onClick={()=>setTab("leads")}><MessageSquareText/>Enquiries <b>{counts.new}</b></button>{sections.map(([name,Icon])=><button className={tab===name?"active":""} key={name} onClick={()=>setTab(name)}><Icon/>{name}</button>)}</nav><button className="admin-logout" onClick={logout}><LogOut/>Logout</button></aside><section className="admin-main"><header><button className="admin-menu" onClick={()=>setMobile(true)}><Menu/></button><div><span>RS Construction</span><strong>{tab==="overview"?"Dashboard":tab}</strong></div><div className="admin-header-actions"><a href="/api/admin/export"><Download/>Export CSV</a><button onClick={save}><Save/>{saved?"Saved":"Save changes"}</button></div></header><div className="admin-content">{tab==="overview"&&<><div className="admin-welcome"><div><span>Dashboard overview</span><h1>Good decisions start with clear data.</h1><p>Monitor lead flow and keep every public-facing section current.</p></div><BriefcaseBusiness/></div><div className="admin-stats">{Object.entries(counts).map(([k,v])=><article key={k}><small>{k}</small><strong>{v}</strong><span>Current total</span></article>)}</div><div className="admin-panel"><h2>Lead sources</h2><div className="source-bars">{["Enquiry Popup","Contact Form","Package","Project"].map(name=><div key={name}><span>{name}</span><i><b style={{width:`${Math.max(8,leads.filter(x=>String(x.source).includes(name)).length*12)}%`}}/></i></div>)}</div></div></>}
 {tab==="leads"&&<div className="admin-panel"><div className="panel-title"><div><span>Lead management</span><h1>Enquiries</h1></div><a href="/api/admin/export"><Download/>Export CSV</a></div><div className="admin-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>New</option><option>Contacted</option><option>Closed</option></select></div><div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Source</th><th>Name</th><th>Mobile</th><th>Location</th><th>Status</th></tr></thead><tbody>{filtered.map(lead=>{const i=leads.findIndex(x=>x.id===lead.id);return <tr key={String(lead.id)}><td>{new Date(String(lead.createdAt)).toLocaleDateString()}</td><td>{String(lead.source)}</td><td>{String(lead.name)}</td><td>{String(lead.mobile)}</td><td>{String(lead.location||"—")}</td><td><select value={String(lead.status)} onChange={e=>setLeads(leads.map((x,n)=>n===i?{...x,status:e.target.value}:x))}><option>New</option><option>Contacted</option><option>Closed</option></select></td></tr>})}</tbody></table></div></div>}
 {tab!=="overview"&&tab!=="leads"&&<div className="admin-panel editor-panel"><span>Dynamic content manager</span><h1>{tab}</h1><p>Edit this section as structured JSON. Changes are validated before being accepted and saved through the protected admin API.</p><div className="admin-upload"><label>Upload image<input type="file" accept="image/*" onChange={uploadImage}/></label>{upload&&<code>{upload}</code>}</div><textarea key={tab} defaultValue={JSON.stringify(site[tab],null,2)} onBlur={e=>updateJson(tab,e.target.value)} spellCheck={false}/><button className="button primary" onClick={save}><Save/>Save {tab}</button></div>}</div></section></main>
}
